config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_page#index'
    get 'services', to: 'static_page#services'
    get 'contact', to: 'static_page#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController

def index
end

def about
end 

def contact
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JuniorLandscape</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flex-content-container">
      <!-- navbar -->
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="navbar navbar-light bg-light">
          <%= link_to root_path class: "navbar-brand" do %>
            <%= image_tag('jrlogo.png') %>
          <% end %>
        </nav>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item active">
              <%= link_to 'Home', root_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Services', services_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Contact', contact_path, class: 'nav-link' %>
            </li>
          </ul>
          
        </div>
      </nav>


     <%= yield %>
    </div>

    <div id="footer">
      <div class="container">
        <b>Footer Here</b>
        <br />
        <%= link_to 'Link', '#' %>
      </div>
    </div>
  </body>
</html>

app/views/static_page/contact.html.erb
<h1 style="text-align: center;">Contact Information</h1>
<br />
<br />

<div class="container">
  <div class="row">
    <div class="col-sm-4 contact_info" style="background-color:rgb(245, 245, 240);">
      <img src="/assets/contact_logo.png" class = "img-fluid cont_logo" />
      <p class="contact_title">
      JR Landscaping
      </p>
      <br />
      <p>My name is Junior Lara, Proud owner of JR Landscaping. I am a service oriented individual wanting to take care of the hard work so you don't have to. So sit back, give me a call, crack a cold one open(or pop open a bottle if that's your choice), and let me take care of your lawn.</p>
      <p><span>&#9742;</span> 111-222-3333</p>
      <p><span>&#9993;</span> jrlandscaping@gmail.com</p>
      <p><span>&#10097;</span> Bryan, Texas</p>
    </div>
    <div class="col-sm-8" style="background-color:rgb(245, 245, 240);">
      <img src="/assets/setup.jpg" class = "img-fluid setup_pic" />
    </div>
  </div>
</div>

app/views/static_page/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>You'll Grow It, We'll Mow It</h1>
    <br />
    <h2>Affordable Prices For Every Budget</h2>
    <br />
    <%= link_to 'Hire Me', contact_path, class: 'btn btn-outline-success' %>
    <br /><br />
  </div>
</div>

app/views/static_page/services.html.erb
<div class="title_services">
  <h1>Our Solutions</h1>
</div>
<br />

<div class="services_done">
  <h2>Full Lawn Services</h2>
</div>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img src="/assets/slider1.jpg" class = "img-fluid" />
    </div>
    <div class="carousel-item">
      <img src="/assets/slider2.jpg" class = "img-fluid" />
    </div>
    <div class="carousel-item">
      <img src="/assets/slider3.jpg" class = "img-fluid" />
   </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>

<br />

<div class="services_done">
  <h2>Tree Removal</h2>
</div>

<div class="pic">
  <img src="/assets/slider5.jpg" class = "img-fluid" />
</div>

<br />

<div class="services_done">
  <h2>Fencing</h2>
</div>

<div class="pic">
  <img src="/assets/slider6.jpg" class = "img-fluid" />
</div>

<br />

<div class="services_done">
  <h2>Leaf Removal</h2>
</div>

<div class="pic">
  <img src="/assets/slider7.jpg" class = "img-fluid" />
</div>

<br />